products:
  image:
    files:
      path: ${PRODUCTS_IMAGES}

spring:
  application:
    name: ecommerce
  servlet:
    multipart:
      max-file-size: 2048KB
      max-request-size: 500KB
  web:
    resources:
      static-locations: classpath:/static, ${STATIC_FILES_PATH}
  jpa:
    generate-ddl: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
flyway:
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  schemas: ${DB_DATABASE}
  url: ${DB_URL}
  locations: db/migration

