services:
  ecommerce:
    image: openjdk:22
    entrypoint: "java -jar /usr/src/myapp/ecommerce-0.0.1-SNAPSHOT.jar"
    volumes:
      - ${JAR_PATH}:/usr/src/myapp
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_DATABASE=ecommerce
      - DB_URL=jdbc:mysql://ecommerce-db:3306/ecommerce
      - PRODUCTS_IMAGES=/usr/src/myapp/static-files/images
      - STATIC_FILES_PATH=file:/usr/src/myapp/static-files
    depends_on:
      - ecommerce-db
    networks:
      - ecommerce-network
  ecommerce-db:
    image: mysql:9.3.0
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=ecommerce
    networks:
       - ecommerce-network
    
networks:
  ecommerce-network:
    driver: bridge